---

services:
  api:
    container_name: api
    depends_on:
      database:
        condition: service_started
    env_file:
      ./silent-api/.env
    environment:
      POSTGRES_DB: sg
      POSTGRES_HOST: database
      POSTGRES_USER: sg
      POSTGRES_PASSWORD: default
      POSTGRES_PORT: 5432
      CORS_ALLOWED_ORIGINS: https://silentguard-local.ricardocampos.dev.br:5173
      TARGET_ENV: development
      API_LOGGING_LEVEL: INFO
    ports:
      - "8443:8443"
      - "5005:5005"
    image: maven:3.9.9-eclipse-temurin-21
    entrypoint: './mvnw -ntp spring-boot:run -Dspring-boot.run.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005" -Dmaven.plugin.validation=VERBOSE'
    working_dir: /app
    volumes:
      - "./silent-api:/app"
    healthcheck:
      test: curl -f -k https://localhost:8443/actuator/health | grep '"status":"UP"'
      interval: 1m30s
      timeout: 15s
      retries: 3
      start_period: 10s

  database:
    container_name: database
    image: postgres:15.8-bookworm
    environment:
      POSTGRES_DB: sg
      POSTGRES_USER: sg
      POSTGRES_PASSWORD: default
    ports:
      - "5432:5432"
    healthcheck:
      test: psql -q -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c 'SELECT 1'
      interval: 1m30s
      timeout: 15s
      retries: 3
      start_period: 10s
