# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  docker-build-app:
    desc: Build the silent-app prod-ready docker image, tagging it as candidate
    cmd: docker build --build-arg VITE_BUILD="v999-$(date '+%Y-%m-%d-%H%M%S')" --build-arg SOURCE_PR="v999-123456789-$(date '+%Y-%m-%d-%H%M%S')" -f silent-app/Dockerfile.dev -t ghcr.io/rmcampos/silent-guard/silent-app:candidate ./silent-app

  docker-build-api:
    desc: Build the silent-api prod-ready docker image, tagging it as candidate
    cmd: docker build --build-arg BUILD="v999-$(date '+%Y-%m-%d-%H%M%S')" --build-arg SOURCE_PR="v999-123456789-$(date '+%Y-%m-%d-%H%M%S')" -f silent-api/Dockerfile.dev -t ghcr.io/rmcampos/silent-guard/silent-api:candidate ./silent-api

  prod-up-app:
    desc: Speed up the silent-app prod-like image, building it if required
    cmd: docker compose -f docker-compose.prod.yml up -d silent-app

  prod-up-api:
    desc: Speed up the silent-api prod-like image, building it if required
    cmd: docker compose -f docker-compose.prod.yml up -d silent-api

  prod-up-db:
    desc: Start the database container
    cmd: docker compose -f docker-compose.prod.yml up -d silent-db

  prod-up:
    desc: Speed up the prod-like images for both silent-api and silent-app, building them if required
    cmd: docker compose -f docker-compose.prod.yml up -d

  prod-stop:
    desc: Stop prod containers
    cmd: docker compose -f docker-compose.prod.yml stop

  prod-tier-down:
    desc: Stop and remove prod containers
    cmd: docker compose -f docker-compose.prod.yml down --remove-orphans

  dev-run-app:
    desc: Get the silent-app up and running locally inside docker ready for development
    cmd: docker compose -f docker-compose.dev.yml up -d silent-app

  dev-run-api:
    desc: Get the silent-api up and running locally inside docker ready for development
    cmd: docker compose -f docker-compose.dev.yml up -d silent-api

  dev-run-db:
    desc: Get the silent-db up and running locally inside docker ready for development
    cmd: docker compose -f docker-compose.dev.yml up -d silent-db

  dev-run:
    desc: Get both silent-app and silent-api up and running locally inside docker ready for development
    cmd: docker compose -f docker-compose.dev.yml up -d

  dev-stop:
    desc: Stop dev containers
    cmd: docker compose -f docker-compose.dev.yml stop

  dev-tier-down:
    desc: Stop and remove dev containers
    cmd: docker compose -f docker-compose.dev.yml down --remove-orphans
