name: App - Main

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'silent-app/**/*.html'
      - 'silent-app/**/*.png'
      - 'silent-app/**/*.json'
      - 'silent-app/**/*.txt'
      - 'silent-app/**/*.ts'
      - 'silent-app/**/*.tsx'
      - 'silent-app/**/*.js'
      - 'silent-app/Dockerfile'
      - 'silent-app/Caddyfile'

jobs:
  silent-app-code-checks:
    name: App Code Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Clean and Install
        run: cd silent-app && npm ci
      - name: Build
        run: cd silent-app && npm run build
      - name: Lint
        run: cd silent-app && npm run lint

  image-promotion-and-deploy:
    name: Image promotion and deployment
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DEPLOY_DOMAIN: ${{ vars.DEPLOY_DOMAIN }}
      GHCR_USERNAME: ${{ vars.GHCR_USERNAME }}
      GHCR_PASSWORD: ${{ secrets.GHCR_PASSWORD }}
      DOKPLOY_API_KEY: ${{ secrets.DOKPLOY_API_KEY }}
      DOKPLOY_APP_APPID: ${{ secrets.DOKPLOY_APP_APPID }}
    steps:
      - uses: docker/login-action@v3
        name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image with source tag
        run: docker pull ghcr.io/rmcampos/silent-guard/silent-app:candidate

      - name: Extract PR number using docker inspect
        id: inspect
        run: |
          SOURCE_PR=$(docker inspect ghcr.io/rmcampos/silent-guard/silent-app:candidate | jq -r '.[0].Config.Env[] | select(startswith("SOURCE_PR="))' | sed -n 's/SOURCE_PR=\(v[0-9]*\).*/\1/p')
          echo "SOURCE_PR=$SOURCE_PR" >> $GITHUB_ENV
          echo "source_pr=$SOURCE_PR" >> $GITHUB_OUTPUT

      - name: Re-tag the image
        run: docker tag ghcr.io/rmcampos/silent-guard/silent-app:candidate ghcr.io/rmcampos/silent-guard/silent-app:prod-${{ steps.inspect.outputs.source_pr }}

      - name: Push new tag
        run: docker push ghcr.io/rmcampos/silent-guard/silent-app:prod-${{ steps.inspect.outputs.source_pr }}

      - name: Checking cURL version
        run: curl --version

      - name: Update image tag to be deployed
        uses: nick-fields/retry@v3.0.2
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: |
            response=$(curl -X POST \
              "${DEPLOY_DOMAIN}/api/application.saveDockerProvider" \
              --max-time 30 \
              -H "accept: application/json" \
              -H "Content-Type: application/json" \
              -H "x-api-key: ${DOKPLOY_API_KEY}" \
              -d '{
                "dockerImage": "ghcr.io/rmcampos/silent-guard/silent-app:prod-${{ steps.inspect.outputs.source_pr }}",
                "applicationId": "'"${DOKPLOY_APP_APPID}"'",
                "username": "'"${GHCR_USERNAME}"'",
                "password": "'"${GHCR_PASSWORD}"'",
                "registryUrl": "ghcr.io"
                }' \
              -w "\n%{http_code}" \
              -s)

            status_code=$(echo "$response" | tail -n1)
            echo "Status code: $status_code"

            if [ "$status_code" != "200" ]; then
              body=$(echo "$response" | sed '$d')
              
              echo "Update failed with status code $status_code"
              echo -e "Response body: $body"
              exit 1
            else
              echo "Updated succeeded!"
            fi

      - name: Trigger Deployment
        uses: nick-fields/retry@v3.0.2
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: |
            sleep 15

            response=$(curl -X POST \
              "${DEPLOY_DOMAIN}/api/application.deploy" \
              --max-time 30 \
              -H "accept: application/json" \
              -H "x-api-key: ${DOKPLOY_API_KEY}" \
              -H "Content-Type: application/json" \
              -d "{\"applicationId\":\"${DOKPLOY_APP_APPID}\"}" \
              -w "\n%{http_code}" \
              -s)

            status_code=$(echo "$response" | tail -n1)
            echo "Status code: $status_code"

            if [ "$status_code" != "200" ]; then
              body=$(echo "$response" | sed '$d')
              
              echo "Deployment failed with status code $status_code"
              echo -e "Response body: $body"
              exit 1
            else
              echo "Deployment succeeded!"
            fi

      - name: Verifying post deployment
        run: |
          # Wait for deployment to complete
          sleep 15
    
          if ! curl -s -f "${{ vars.APP_URL }}/" > /dev/null; then
            echo "Prod environment is not healthy"
            exit 1
          else
            echo "Prod environment is healthy"
          fi
