name: API - PR

on:
  pull_request:
    paths:
      - 'silent-api/**'

concurrency:
  group: silent-api-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  java-code-checks:
    name: API Code Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v4.2.3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: cd silent-api && ./mvnw --no-transfer-progress clean compile -DskipTests

      - name: Google Check-Style
        run: cd silent-api && ./mvnw --no-transfer-progress checkstyle:checkstyle -Dskip.checkstyle=false

  silent-api-docker-build:
    name: Build API Docker image
    runs-on: ubuntu-latest
    needs: java-code-checks
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx

      - uses: docker/login-action@v3
        name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./silent-api
          tags: ghcr.io/rmcampos/silent-guard/silent-api:candidate
          build-args: |
            BUILD=v${{ github.event.number }}-${{ steps.date.outputs.date }}
            SOURCE_PR=v${{ github.event.number }}-${{ github.run_id }}-${{ steps.date.outputs.date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
