name: App - PR

on:
  pull_request:
    paths:
      - 'silent-app/**'

concurrency:
  group: silent-app-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  silent-app-code-checks:
    name: App Code Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        name: Set up Node
        with:
          node-version: '22'
      - name: Clean and Install
        run: cd silent-app && npm ci
      - name: Build
        run: cd silent-app && npm run build
      - name: Lint
        run: cd silent-app && npm run lint

  silent-app-docker-build:
    name: Build App Docker image
    runs-on: ubuntu-latest
    needs: silent-app-code-checks
    permissions:
      contents: read
      packages: write
    env:
      VITE_BUILD: silent-app:${{ github.event.number }}
      VITE_BACKEND_API: ${{ secrets.VITE_BACKEND_API }}/server
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx
      
      - uses: docker/login-action@v3
        name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./silent-app
          tags: ghcr.io/rmcampos/silent-guard/silent-app:candidate
          build-args: |
            VITE_BUILD=v${{ github.event.number }}-${{ steps.date.outputs.date }}
            SOURCE_PR=v${{ github.event.number }}-${{ github.run_id }}-${{ steps.date.outputs.date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
